### ISSUE TITLE
HTTPS Everywhere Update Overrides Darkweb Everywhere

### ISSUE THREAD

**Issue by stephenjudge** [chris-barry/darkweb-everywhere#28]
There is some code in Darkweb Everywhere that is called the HTTPS Everywhere update script during automatic or manual update. The problem is during such update HTTP Everywhere is then installed over Darkweb Everywhere and you then have to go an re-install Darkweb Everywhere.

**Comment by colinmahns** [comment]
Closing this issue as we've deprecated our extension. See https://github.com/chris-barry/darkweb-everywhere/blob/8124265a4dbc432dd4f33e1e97479752452149c4/README.md
