### ISSUE TITLE
SSL Observatory Preferences Not Saved

### ISSUE THREAD

**Issue by stephenjudge** [chris-barry/darkweb-everywhere#34]
I have opted into all the SSL Observatory Preferences but my opt-ins are not being saved. Also the option for the Advanced Preferences is not working, is this intentional? And if so why?

**Comment by colinmahns** [comment]
Closing this issue as we've deprecated our extension. See https://github.com/chris-barry/darkweb-everywhere/blob/8124265a4dbc432dd4f33e1e97479752452149c4/README.md
