### ISSUE TITLE
SHA Checksum Does Not Match?

### ISSUE THREAD

**Issue by ph4tsn4pch4t** [chris-barry/darkweb-everywhere#36]
Hello,

I've tried to download darkweb-everywhere-master.zip, and have gotten a checksum that doesn't match the one I copied from this page. 

The checksum I got from terminal: 
48f94391d79bbd150f666594f260da3393a7d868

The checksum from this site: 
511363358fea0350cfc0c325ee854f7cc8361a6c

Are these two different versions/branches, and I'm copying the wrong checksum from the website, or... MITM?

I hope I'm not wasting your time!

Best wishes,
Noob

**Comment by chris-barry** [comment]
Hi,

So I think you are downloading from master. To check the sum you should compare the release from https://github.com/chris-barry/darkweb-everywhere/releases . master is generally not signed
-- 
Chris Barry
