### ISSUE TITLE
You can still use the rules even if it's depreciated

### ISSUE THREAD

**Issue by cypherpunk** [chris-barry/darkweb-everywhere#40]
Can't you just copy all the XML rules into the UserRules directory of HTTPS everywhere?
`Tor Browser/Browser/TorBrowser/Data/Browser/profile.default/HTTPSEverywhereUserRules`

In my test this worked without any problems. And AFAIK it should be as secure as using this extension.
The only issue I noticed is that you cannot disable or enable these manually added rulesets.

So maybe add this 'workaround' to the Readme and continue this repo as a pure rulesets repo.

**Comment by chris-barry** [comment]
This is right. I'll add it to the redme so people don't have to wander here.
